### ISSUE TITLE
Unable to follow all the steps - someone better double check the steps

### ISSUE THREAD

**Issue by davidstanleigh** [MicrosoftLearning/AZ-100-MicrosoftAzureInfrastructureDeployment#40]
Unable to follow all the steps - someone better double check the steps

**Comment by polichtm** [comment]
Hi David,
which steps are you referring to?
rgds
Marcin

**Comment by davidstanleigh** [comment]
Hi Marcin,

I did not take note exactly, but at the end I did not get the expected result, I spent a couple of hours trying to perform each step and it is a bit disappointing that it not worked at the end. I suggest to add screen shots if possible GIT hub. Thanks.

**Comment by polichtm** [comment]
Hi David,
which lab are you referring to?
rgds
Marcin

**Comment by davidstanleigh** [comment]
Hi Marcin,

This one,
az-100-01b__instructions.md<https://github.com/MicrosoftLearning/AZ-100-MicrosoftAzureInfrastructureDeployment/blob/master/Instructions/az-100-01b__instructions.md>

Confusing Tagging initiative<https://github.com/MicrosoftLearning/AZ-100-MicrosoftAzureInfrastructureDeployment/commit/6ee26a29dff5774e18cdc9c21739a7c562768de7>


I honestly tried to follow every step but its hard sometimes and the end result was not as expected, please have someone new as me to follow the steps.

Thanks,

Kind regards,

David

David Peña
Infrastructure Management Sr. Analyst
ITO
Mobile: + 502 5696-0259
Guatemala
david.pena@atos.net
Atos.net
[atos_logotype]

This e-mail and the documents attached are confidential and intended solely for the addressee; it may also be privileged. If you receive this e-mail in error, please notify the sender immediately and destroy it. As its integrity cannot be secured on the Internet, the Atos group liability cannot be triggered for the message content. Although the sender endeavors to maintain a computer virus-free network, the sender does not warrant that this transmission is virus-free and will not be liable for any damages resulting from any virus transmitted.

**Comment by polichtm** [comment]
Hi David,
would you mind giving me a couple of examples?
rgds
Marcin

**Comment by davidstanleigh** [comment]
I did not took note, but the last exercise before the locks I did not had the VM that it said and the name was incorrect,

Kind regards,

David

David Peña
Infrastructure Management Sr. Analyst
ITO
Mobile: + 502 5696-0259
Guatemala
david.pena@atos.net
Atos.net
[atos_logotype]

This e-mail and the documents attached are confidential and intended solely for the addressee; it may also be privileged. If you receive this e-mail in error, please notify the sender immediately and destroy it. As its integrity cannot be secured on the Internet, the Atos group liability cannot be triggered for the message content. Although the sender endeavors to maintain a computer virus-free network, the sender does not warrant that this transmission is virus-free and will not be liable for any damages resulting from any virus transmitted.

**Comment by polichtm** [comment]
Hi David,
would you mind stepping through this lab again when you have a chance and let me know if there is anything that you find incorrect or unclear? I made a few changes - I'm hoping that these will address your concerns.
Btw. pls note that we changed the format of instructions from "click-through" (where each step was described in a very detailed fashion) to a "higher-level" approach. This was intended to minimize dependencies on specific elements in the Azure portal inteface, which change quite frequently (btw. the same would apply if we were to include screenshots). Another important consideration was to ensure that students learn the interface and its features, rather than simply follow directions (which, somewhat ironically, hinders the learning process).
However, we always welcome any constructive feedback - so pls let us know how, in your opinion, we further improve students' (and MCTs) experience.
rgds
Marcin

**Comment by davidstanleigh** [comment]
ok thanks, will try to go through again, the screen shot might help to know where is that specific step or if we are in the correct option or feature,

thanks
David

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by polichtm** [comment]
Hi David,
did you have a chance to look into this?
rgds
Marcin

**Comment by polichtm** [comment]
Closing due to lack of response
